title:  Hoiblog
subtitle: Shuenhoy's Blog
manage:
  type: github
  user: Shuenhoy
  repo: shuenhoy.github.com
  version: 1
  always: true
duoshuo_id: shuenhoyblog

routes:
  post: "#!/post/:name"
  page: "#!/:name"
